name: GitHub ActionTest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ActionTest
      run: |
        echo 色々実験
        ls -la
        ls -la ..
        pwd
        ls -la /
        node
        gcc
        
