name: GitHub ActionTest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ActionTest
      run: |
        echo ふぉっふぉっふぉっふぉ
        echo ぐふぉぉ
