name: GitHub ActionTest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ActionTest
      run: |
        echo nodeのバージョン
        node -v
        echo テキスト作成 > ../test.txt
        echo ファイルリスト
        ls -la ..
        echo ルートファイル
        ls -la /

        
